sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - "3.4"

before_install:
  - docker build -t bionitio-boot boot/

script:
  - docker run --rm bionitio-boot -h
  - docker run -it -v "$TRAVIS_BUILD_DIR:/out" --rm bionitio-boot -i python -n biodemo -c BSD-3-Clause -a 'Example Author Name' -e 'example@email.address.com' -l logfile -v
  - boot/bionitio-boot-test.sh
