
# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

addons:
  apt:
    packages:
      npm


before_install:
  - ./.travis/install-dependencies.sh

script: ./.travis/test-all.sh
